name: Deploy Frontend to AWS S3 Bucket Web-Hosting

on:
  push:
    tags:
      - fe-*

env: 
  S3_BUCKET: ${{ vars.BUCKET_NAME }}

permissions:
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Build and sync Vite app to S3 bucket
        working-directory: frontend
        run: |
          npm install
          npm run build
          aws s3 sync dist s3://$S3_BUCKET --delete